server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
######Spring-Cloud Consul for Service Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-agent-address: true   #优先使用服务器IP进行注册
  service.name: ${spring.application.name}